In [10]:
import pandas as pd

df = pd.read_csv("../data/customer_churn.csv")

df.head()

,CustomerID,Age,Gender,SubscriptionType,MonthlyCharges,TenureMonths,SupportTickets,PaymentMethod,SatisfactionScore,UsageHoursPerWeek,Churn
0,1,56,Male,Premium,766,26,5,UPI,8,37,No
1,2,69,Female,Basic,430,2,0,Net Banking,2,39,No
2,3,46,Male,Basic,1073,23,9,Credit Card,1,20,Yes
3,4,32,Male,Premium,773,41,7,UPI,4,10,Yes
4,5,60,Female,Basic,439,22,1,UPI,4,10,No

In [19]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         3000 non-null   int64
 1   Age                3000 non-null   int64
 2   Gender             3000 non-null   str
 3   SubscriptionType   3000 non-null   str
 4   MonthlyCharges     3000 non-null   int64
 5   TenureMonths       3000 non-null   int64
 6   SupportTickets     3000 non-null   int64
 7   PaymentMethod      3000 non-null   str
 8   SatisfactionScore  3000 non-null   int64
 9   UsageHoursPerWeek  3000 non-null   int64
 10  Churn              3000 non-null   str
dtypes: int64(7), str(4)
memory usage: 257.9 KB

In [27]:
# Check missing values
df.isnull().sum()

CustomerID           0
Age                  0
Gender               0
SubscriptionType     0
MonthlyCharges       0
TenureMonths         0
SupportTickets       0
PaymentMethod        0
SatisfactionScore    0
UsageHoursPerWeek    0
Churn                0
dtype: int64

In [34]:
# Statistical summary
df.describe()

,CustomerID,Age,MonthlyCharges,TenureMonths,SupportTickets,SatisfactionScore,UsageHoursPerWeek
count,3000.000000,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,43.563000,1106.05000,30.010000,4.492000,5.517000,25.139333
std,866.169729,14.941791,514.53623,17.045725,2.858437,2.884063,14.093336
min,1.000000,18.000000,200.00000,1.000000,0.000000,1.000000,1.000000
25%,750.750000,31.000000,666.75000,15.000000,2.000000,3.000000,13.000000
50%,1500.500000,44.000000,1101.00000,29.000000,4.000000,6.000000,25.000000
75%,2250.250000,56.000000,1551.00000,45.000000,7.000000,8.000000,37.000000
max,3000.000000,69.000000,1998.00000,59.000000,9.000000,10.000000,49.000000

In [40]:
import plotly.express as px

fig = px.histogram(
    df,
    x="Churn",
    color="Churn",
    title="Customer Churn Distribution"
)

fig.show()

In [45]:
import plotly.io as pio
pio.renderers.default = "browser"

In [55]:
fig = px.histogram(
    df,
    x="Gender",
    color="Churn",
    barmode="group",
    title="Gender vs Churn"
)

fig.show()

In [56]:
fig = px.histogram(
    df,
    x="SubscriptionType",
    color="Churn",
    barmode="group",
    title="Subscription Type vs Churn"
)

fig.show()

In [58]:
fig = px.histogram(
    df,
    x="Age",
    nbins=20,
    title="Age Distribution"
)

fig.show()

In [59]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_columns = ["Gender", "SubscriptionType", "PaymentMethod", "Churn"]

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

df.head()

,CustomerID,Age,Gender,SubscriptionType,MonthlyCharges,TenureMonths,SupportTickets,PaymentMethod,SatisfactionScore,UsageHoursPerWeek,Churn
0,1,56,1,2,766,26,5,2,8,37,0
1,2,69,0,0,430,2,0,1,2,39,0
2,3,46,1,0,1073,23,9,0,1,20,1
3,4,32,1,2,773,41,7,2,4,10,1
4,5,60,0,0,439,22,1,2,4,10,0

In [60]:
df.to_csv("../data/customer_churn_processed.csv", index=False)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [61]:
from sklearn.model_selection import train_test_split

X = df.drop("Churn", axis=1)
y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (2400, 10)
Testing data: (600, 10)

In [62]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [63]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       490
           1       1.00      1.00      1.00       110

    accuracy                           1.00       600
   macro avg       1.00      1.00      1.00       600
weighted avg       1.00      1.00      1.00       600

In [67]:
import joblib

joblib.dump(model, "../models/churn_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [68]:
import os

os.makedirs("../models", exist_ok=True)

import joblib
joblib.dump(model, "../models/churn_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [69]:
print(list(X.columns))

['CustomerID', 'Age', 'Gender', 'SubscriptionType', 'MonthlyCharges', 'TenureMonths', 'SupportTickets', 'PaymentMethod', 'SatisfactionScore', 'UsageHoursPerWeek']

In [70]:
print("\n".join(X.columns))

CustomerID
Age
Gender
SubscriptionType
MonthlyCharges
TenureMonths
SupportTickets
PaymentMethod
SatisfactionScore
UsageHoursPerWeek